# Generated by Django 4.0.3 on 2022-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_blog_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
