# Generated by Django 4.0.3 on 2022-06-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
