# Generated by Django 4.0.3 on 2022-07-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_blog_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id']},
        ),
    ]
